# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc57e41b1299a1b4bb6931aae7e08a479436e7e647d9b8fe66b716812429f7e79d4e04508a5c6d55c5350a9e9727bf209907bcbf3f6d10c2f6c2840cf751d0ac

test:
  secret_key_base: b7b5271cd0761bbcc7be9ae085129e8da403c9adea7f22488b13fd740dd94f8c7d0263f4b6f2909d6059dfd0ab231379a26680a5a62840c64180e9484677f145

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
